# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonorInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=30)),
                ('Age', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('group', models.IntegerField(choices=[(1, 'O+'), (2, 'O-'), (3, 'A+'), (4, 'A-'), (5, 'B+'), (6, 'B-'), (7, 'AB+'), (8, 'AB-')], default=1)),
                ('reason', models.IntegerField(choices=[(1, 'Interested'), (2, 'Emergency'), (3, 'Other')], default=1)),
            ],
        ),
    ]
