# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorinformation',
            old_name='Name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='donorinformation',
            name='last_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donorinformation',
            name='Age',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='donorinformation',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donorinformation',
            name='group',
            field=models.IntegerField(choices=[(0, 'Blood Group'), (1, 'O+'), (2, 'O-'), (3, 'A+'), (4, 'A-'), (5, 'B+'), (6, 'B-'), (7, 'AB+'), (8, 'AB-')], default=0),
        ),
        migrations.AlterField(
            model_name='donorinformation',
            name='reason',
            field=models.IntegerField(choices=[(0, 'Reason'), (1, 'Interested'), (2, 'Emergency'), (3, 'Other')], default=0),
        ),
    ]
