# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20180720_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorinformation',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donorinformation',
            name='group',
            field=models.IntegerField(choices=[(0, 'Blood Group'), (1, 'O+'), (2, 'O-'), (3, 'A+'), (4, 'A-'), (5, 'B+'), (6, 'B-'), (7, 'AB+'), (8, 'AB-')]),
        ),
        migrations.AlterField(
            model_name='donorinformation',
            name='reason',
            field=models.IntegerField(choices=[(0, 'Reason'), (1, 'Interested'), (2, 'Emergency'), (3, 'Other')]),
        ),
    ]
